# generated by datamodel-codegen:
#   filename:  report_types.yaml
#   timestamp: 2024-07-15T18:31:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Category(Enum):
    potential = "potential"
    optional = "optional"
    mandatory = "mandatory"


class Incident(BaseModel):
    uri: str
    message: str
    codeSnip: Optional[str] = None
    lineNumber: Optional[int] = None
    variables: Optional[Dict[str, Any]] = None


class Link(BaseModel):
    url: str
    title: Optional[str] = None


class Violation(BaseModel):
    description: Optional[str] = None
    category: Optional[Category] = None
    labels: Optional[List[str]] = None
    incidents: Optional[List[Incident]] = None
    links: Optional[List[Link]] = None
    extras: Optional[str] = None
    effort: Optional[int] = None


class RuleSet(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    tags: Optional[List[float]] = None
    violations: Optional[Dict[str, Violation]] = None
    errors: Optional[Dict[str, str]] = None
    unmatched: Optional[List[str]] = None
    skipped: Optional[List[str]] = None


class AnalysisReport(RootModel[List[RuleSet]]):
    root: List[RuleSet] = Field(..., title="AnalysisReport")
