FROM registry.access.redhat.com/ubi9/ubi:latest
RUN dnf -y update && dnf -y install python3-pip python3-pyyaml && dnf clean all
RUN pip install --no-cache aiohttp
EXPOSE 8080
COPY kai.py /usr/local/bin/kai.py
ENTRYPOINT ["python3", "-u", "/usr/local/bin/kai.py"]
