version: "3"

# TODO: Unify hub importer variables with kai variables. They are currently not
# stored on KaiConfig.

x-kai-variables: &kai-variables
  KAI__LOG_LEVEL: info
  KAI__LOG_DIR: /podman_compose/logs
  KAI__GUNICORN_WORKERS: 8
  KAI__GUNICORN_BIND: "0.0.0.0:8080"
  KAI__HUB_URL: ${HUB_URL:-https://tackle-konveyor-tackle.apps.example.com/hub}
  KAI__IMPORTER_ARGS:
  KAI__DEMO_MODE: "True"
  USE_HUB_IMPORTER: ${USE_HUB_IMPORTER:-False}

  KAI__INCIDENT_STORE__ARGS__PROVIDER: postgresql
  KAI__INCIDENT_STORE__ARGS__DATABASE: kai
  KAI__INCIDENT_STORE__ARGS__PASSWORD: dog8code
  KAI__INCIDENT_STORE__ARGS__USER: kai
  KAI__INCIDENT_STORE__ARGS__HOST: kai_db

x-db-variables: &db-variables
  POSTGRESQL_DATABASE: "${KAI__INCIDENT_STORE__ARGS__DATABASE:-kai}"
  POSTGRESQL_PASSWORD: "${KAI__INCIDENT_STORE__ARGS__PASSWORD:-dog8code}"
  POSTGRESQL_USER: "${KAI__INCIDENT_STORE__ARGS__USER:-kai}"
  POSTGRESQL_HOST: "${KAI__INCIDENT_STORE__ARGS__HOST:-kai_db}"

services:
  kai:
    environment:
      <<: [*kai-variables, *db-variables]
      # Do not edit the variables below otherwise you risk committing keys to a
      # public repo These lines will pass in the environment variables from your
      # host system.
      GENAI_KEY:
      OPENAI_API_BASE:
      OPENAI_API_KEY:
      GOOGLE_API_KEY:
    image: ${IMAGE:-quay.io/konveyor/kai}:${TAG:-stable}
    volumes:
      - ${PWD}:/podman_compose:rw,Z
      - ${PWD}/logs:/podman_compose/logs:rw,Z,U
    ports:
      - "8080:8080"
    depends_on:
      kai_db:
        condition: service_healthy
  kai_hub_importer:
    environment:
      <<: [*kai-variables, *db-variables]
      MODE: importer
    image: ${IMAGE:-quay.io/konveyor/kai}:${TAG:-stable}
    volumes:
      - ${PWD}:/podman_compose:rw,Z
      - ${PWD}/logs:/podman_compose/logs:rw,Z,U
    depends_on:
      kai_db:
        condition: service_healthy
    profiles:
      - use_hub_importer
  kai_db:
    image: quay.io/sclorg/postgresql-15-c9s:latest
    environment:
      <<: *db-variables
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 50
    volumes:
      - kai_db_data:/var/lib/postgresql/data:Z
volumes:
  kai_db_data:
