"""Created initial tables

Revision ID: a535c5759c14
Revises: 
Create Date: 2025-05-21 12:53:40.009990

"""

from typing import Sequence, Union


# trunk-ignore-begin(ruff/F401)
import sqlalchemy as sa
from alembic import op

# trunk-ignore-end(ruff/F401)

# revision identifiers, used by Alembic.
revision: str = "a535c5759c14"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
